// Turns Foundry's build output into typed ABIs for every TypeScript service, so the code that
// calls the contracts can never drift from them. Run after `forge build` in contracts/:
//   node packages/chain/scripts/generate-abis.mjs
// CI regenerates and fails if src/abis.ts differs from the committed file.
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../../../contracts/out/', import.meta.url);
const contracts = [
  ['accountFactoryAbi', 'AccountFactory.sol/AccountFactory.json'],
  ['countersignAccountAbi', 'CountersignAccount.sol/CountersignAccount.json'],
  ['orderVaultAbi', 'OrderVault.sol/OrderVault.json'],
];

let out = '// Generated by scripts/generate-abis.mjs from contracts/out. Do not edit by hand.\n';
for (const [name, file] of contracts) {
  const { abi } = JSON.parse(readFileSync(new URL(file, root), 'utf8'));
  if (!Array.isArray(abi) || abi.length === 0)
    throw new Error(`no ABI in ${file}; run forge build in contracts/`);
  out += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(new URL('../src/abis.ts', import.meta.url), out);
console.log(`wrote ${contracts.length} ABIs`);
